=== dingGator/udemy-xml/OrderXML/Order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.bharatthippireddy.com/Order"
	xmlns:tns="http://www.bharatthippireddy.com/Order" 
	elementFormDefault="qualified">
	<element name="Order" type="tns:Order" />
	<complexType name="Order">
		<sequence>
			<element name="customer" type="tns:Customer" />
			<element name="product" type="tns:Product" />
		</sequence>
		<attribute name="Id" type="tns:Id" use="required"  />
	</complexType>
	<complexType name="Customer">
		<sequence>
			<element name="name" type="string" />
			<element name="phone" type="string" minOccurs="0" />
		</sequence>
		<attribute name="Id" type="tns:Id" use="required" />
	</complexType>
	<complexType name="Product">
		<sequence>
			<element name="name" type="tns:String20Chars" minOccurs="1"
				maxOccurs="unbounded" />
			<element name="description" type="tns:String100Chars" />
			<element name="price" type="int" />
			<element name="category" type="tns:CategoryEnumration" />
		</sequence>
		<attribute name="Id" type="tns:Id" use="required" />
	</complexType>

	<simpleType name="String20Chars">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>
	<simpleType name="String100Chars">
		<restriction base="string">
			<maxLength value="100" />
		</restriction>
	</simpleType>

	<simpleType name="CategoryEnumration">
		<restriction base="string">
			<enumeration value="electronics" />
			<enumeration value="books" />
			<enumeration value="shoes" />
		</restriction>
	</simpleType>
	<simpleType name="Id">
		<restriction base="int">
			<pattern value="[0-50]"></pattern>
		</restriction>
	</simpleType>


</schema>

=== dingGator/udemy-xml/OrderXML/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Order Id="1" xmlns:tns="http://www.bharatthippireddy.com/Order"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bharatthippireddy.com/Order Order.xsd ">
	<tns:customer Id="1">
		<tns:name>Kim LChu</tns:name>
	</tns:customer>
	<tns:product Id="1">
		<tns:name>Pride and Prejudice</tns:name>
		<tns:description>classic romance</tns:description>
		<tns:price>5</tns:price>
		<tns:category>books</tns:category>
	</tns:product>
</tns:Order>
